### PR TITLE
build(windows): fix C4244 int to float conversion warning

### LINKED ISSUE #145: build(windows): C4244 `int` to `float` conversion warning
### Description
 While executing msbuild ./VCU-GUI.sln on windows 27 warnings observed 

warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data

https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244?view=msvc-170

### PR DESCRIPTION
**Pull request by niketa282**
## Description

- Fixed C4244 warning through CMake target_compile_options command

Closes #145 

## Checklist

- [x] Code linted with `trunk check`
- [x] Code formatted with `trunk fmt`
- [x] Changes do not generate any new compiler warnings
- [x] Commit messages follow the [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0/#specification)

### CODE REVIEW

**Review by t-bre — CHANGES_REQUESTED** [review]
I'm hesitant to suppress any warning by globally disabling it - would it be possible to instead deal with it on a case-by-case basis? For the narrowing conversion warnings (which I think was all of them?) they can be "suppressed" by explicitly doing `static_cast<T>(x)` which shows clear intent that the conversion is intentional and known to be safe. In some cases it might also be possible to adjust the code to avoid narrowing conversions which would be even better.

**Comment by niketa282** [comment]
> I'm hesitant to suppress any warning by globally disabling it - would it be possible to instead deal with it on a case-by-case basis? For the narrowing conversion warnings (which I think was all of them?) they can be "suppressed" by explicitly doing `static_cast<T>(x)` which shows clear intent that the conversion is intentional and known to be safe. In some cases it might also be possible to adjust the code to avoid narrowing conversions which would be even better.

yup you're absolutely right I guess I was just being lazy but thanks for reminder on bad practice. 

One question I still have is I still get this warning `  C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include\tuple(170,47): warning C4244: 'initializing': conve 
rsion from '_Ty' to '_Ty', possible loss of data [C:\Users\hp\Documents\niketa\vcu-gui\build\VCU-GUI.vcxproj]`
and I can't seem to figure out how to open this standard library file by clicking on the error message on the terminal, it always leads me the .vcxproj file... in other words I don't get where to add the static_cast

**Comment by t-bre** [comment]
> One question I still have is I still get this warning ` C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include\tuple(170,47): warning C4244: 'initializing': conve rsion from '_Ty' to '_Ty', possible loss of data [C:\Users\hp\Documents\niketa\vcu-gui\build\VCU-GUI.vcxproj]` and I can't seem to figure out how to open this standard library file by clicking on the error message on the terminal, it always leads me the .vcxproj file... in other words I don't get where to add the static_cast

Seems to be in reference to `std::tuple` based on the path. Quick search of the codebase and there are only two instances of `std::tuple` which are in `AboutWindow.cpp` and `MetadataEditor.cpp`. In both cases the tuple is used as part of an initialiser list for setting up / laying out some `juce::Label` instances.

My guess is that these lines in `AboutWindow.cpp` are the cause:

```cpp
void AboutWindow::AboutComponent::setupLabels()
{
    using Initialiser = std::tuple<juce::Label*,
                                   const juce::String,
                                   float,
                                   juce::Justification,
                                   juce::Colour>;

    const std::initializer_list<Initialiser> initList
        = {{&appNameLabel,
            juce::String(ProjectInfo::projectName),
            50,
            juce::Justification::bottomLeft,
            juce::Colour(225, 225, 225)},
           {&versionLabel,
            juce::String("Version ") + ProjectInfo::versionString,
            18,
            juce::Justification::topLeft,
            juce::Colour(180, 180, 180)},
           {&commitHashLabel,
            juce::String(GIT_COMMIT_HASH),
            10,
            juce::Justification::centredLeft,
            juce::Colour(120, 120, 120)}};
```

The third parameter in the list is a `float`, but the literals in the initialiser list are `int`. Try changing them to `float` literals (e.g. `50.f` instead of `50`), that might fix it?

**Comment by niketa282** [comment]
> > One question I still have is I still get this warning ` C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include\tuple(170,47): warning C4244: 'initializing': conve rsion from '_Ty' to '_Ty', possible loss of data [C:\Users\hp\Documents\niketa\vcu-gui\build\VCU-GUI.vcxproj]` and I can't seem to figure out how to open this standard library file by clicking on the error message on the terminal, it always leads me the .vcxproj file... in other words I don't get where to add the static_cast
> 
> Seems to be in reference to `std::tuple` based on the path. Quick search of the codebase and there are only two instances of `std::tuple` which are in `AboutWindow.cpp` and `MetadataEditor.cpp`. In both cases the tuple is used as part of an initialiser list for setting up / laying out some `juce::Label` instances.
> 
> My guess is that these lines in `AboutWindow.cpp` are the cause:
> 
> ```c++
> void AboutWindow::AboutComponent::setupLabels()
> {
>     using Initialiser = std::tuple<juce::Label*,
>                                    const juce::String,
>                                    float,
>                                    juce::Justification,
>                                    juce::Colour>;
> 
>     const std::initializer_list<Initialiser> initList
>         = {{&appNameLabel,
>             juce::String(ProjectInfo::projectName),
>             50,
>             juce::Justification::bottomLeft,
>             juce::Colour(225, 225, 225)},
>            {&versionLabel,
>             juce::String("Version ") + ProjectInfo::versionString,
>             18,
>             juce::Justification::topLeft,
>             juce::Colour(180, 180, 180)},
>            {&commitHashLabel,
>             juce::String(GIT_COMMIT_HASH),
>             10,
>             juce::Justification::centredLeft,
>             juce::Colour(120, 120, 120)}};
> ```
> 
> The third parameter in each initialiser is a `float`, but the corresponding literals are `int` in the list. Try changing them to `float` literals (e.g. `50.f` instead of `50`), that might fix it?

yup that worked, thanks!

File: src/gui/appearance/LookAndFeel.cpp [hunk 1]
```diff
@@ -48,8 +48,8 @@ const juce::Typeface::Ptr LookAndFeel::getKarlaTypeface()
 int LookAndFeel::getTabButtonBestWidth(juce::TabBarButton& button,
                                        int /*tabDepth*/)
 {
-    float totalWidth = button.getTabbedButtonBar().getWidth();
-    float numTabs = button.getTabbedButtonBar().getNumTabs();
+    float totalWidth = static_cast<float>(button.getTabbedButtonBar().getWidth());
+    float numTabs = static_cast<float>(button.getTabbedButtonBar().getNumTabs());
```
Comment (t-bre) [inline src/gui/appearance/LookAndFeel.cpp:52]: Very small thing but cases where there is something like `T myVariable = static_cast<T>(somethingElse);`, I suggest using `auto` to declare the variable type. So have `auto myVariable = static_cast<T>(somethingElse);`. For more info see [LLVM "Use Auto Type Deduction to Make Code More Readable"](https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable) and [`clang-tidy` modernize-use-auto rule](https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-auto.html#cast-expressions).

This will be picked up by Trunk so might as well change it so the checks don't fail when I run them before merge!

File: src/gui/windows/AboutWindow.cpp [hunk 2]
```diff
@@ -149,17 +149,17 @@ void AboutWindow::AboutComponent::setupLabels()
...
            {&versionLabel,
             juce::String("Version ") + ProjectInfo::versionString,
-            18,
+            static_cast<float>(18),
             juce::Justification::topLeft,
             juce::Colour(180, 180, 180)},
            {&commitHashLabel,
             juce::String(GIT_COMMIT_HASH),
-            10,
+            static_cast<float>(10),
```
Comment (t-bre) [inline src/gui/windows/AboutWindow.cpp:162]: Same thing here again for all these, use `50.f` instead of `static_cast<float>(50)`.

**Review by t-bre — CHANGES_REQUESTED** [review]

File: src/gui/appearance/LookAndFeel.cpp (hunk 1 above)
Comment (niketa282) [reply src/gui/appearance/LookAndFeel.cpp]: > Very small thing but cases where there is something like `T myVariable = static_cast<T>(somethingElse);`, I suggest using `auto` to declare the variable type. So have `auto myVariable = static_cast<T>(somethingElse);`. For more info see [LLVM "Use Auto Type Deduction to Make Code More Readable"](https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable) and [`clang-tidy` modernize-use-auto rule](https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-auto.html#cast-expressions).
> 
> This will be picked up by Trunk so might as well change it so the checks don't fail when I run them before merge!

Thanks for this document very helpful for learning more! 
A question that came to mind is what are the differences between these [LLVM "Use Auto Type Deduction to Make Code More Readable"](https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable) and https://github.com/cpplint/cpplint is just that the former has rules/coding standards specifically picked up by the clang LLVM based compiler or are there any other differences as well?

**Comment by t-bre** [comment]
Would you mind avoiding not reverting old commits and force pushing when changes are requested? Just leave the original commit and add another one with the new changes. It will all be squashed down into one commit on merge, so the main branch will stay clean - this is part of the reason we use a squash based workflow ([a good article on this which was my motivation for moving to this method](https://blog.dnsimple.com/2019/01/two-years-of-squash-merge/)).

In my opinion, reverting and force pushing is kind of pretending that the development history never happened, which takes away context from reviews and I think defeats some of the purpose of having a version history. It also messes up other people's local versions of the branch - when I pull this I either have to force pull or explicitly delete my local copy of the branch and grab the new version. It's fine to revert stuff locally of course, but once it's pushed I think it's a bad idea. In this case it doesn't really matter since it's just small changes, but in general I think it just adds unnecessary opportunities for problems to happen.

**Comment by niketa282** [comment]
> Would you mind avoiding not reverting old commits and force pushing when changes are requested? Just leave the original commit and add another one with the new changes. It will all be squashed down into one commit on merge, so the main branch will stay clean - this is part of the reason we use a squash based workflow ([a good article on this which was my motivation for moving to this method](https://blog.dnsimple.com/2019/01/two-years-of-squash-merge/)).
> 
> In my opinion, reverting and force pushing is kind of pretending that the development history never happened, which takes away context from reviews and I think defeats some of the purpose of having a version history. It also messes up other people's local versions of the branch - when I pull this I either have to force pull or explicitly delete my local copy of the branch and grab the new version. It's fine to revert stuff locally of course, but once it's pushed I think it's a bad idea. In this case it doesn't really matter since it's just small changes, but in general I think it just adds unnecessary opportunities for problems to happen.

okay will do that. Also any opinion on the question I asked before?

File: src/gui/appearance/LookAndFeel.cpp (hunk 1 above)
Comment (t-bre) [reply src/gui/appearance/LookAndFeel.cpp]: If you think there's a compelling reason to also check things with `cpplint` because `clang-tidy` doesn't cover it, since we're using Trunk (and hopefully will soon have CI integrated) we can easily add that.

Comment (niketa282) [reply src/gui/appearance/LookAndFeel.cpp]: just did some research to better understand this so there's no need for `cpplint` as its just a style checker rather than a static analysis tool

**Comment by niketa282** [comment]
> > Would you mind avoiding not reverting old commits and force pushing when changes are requested? Just leave the original commit and add another one with the new changes. It will all be squashed down into one commit on merge, so the main branch will stay clean - this is part of the reason we use a squash based workflow ([a good article on this which was my motivation for moving to this method](https://blog.dnsimple.com/2019/01/two-years-of-squash-merge/)).
> > In my opinion, reverting and force pushing is kind of pretending that the development history never happened, which takes away context from reviews and I think defeats some of the purpose of having a version history. It also messes up other people's local versions of the branch - when I pull this I either have to force pull or explicitly delete my local copy of the branch and grab the new version. It's fine to revert stuff locally of course, but once it's pushed I think it's a bad idea. In this case it doesn't really matter since it's just small changes, but in general I think it just adds unnecessary opportunities for problems to happen.
> 
> okay will do that. Also any opinion on the question I asked before?

Is there anything else needed to be changed here/kept in mind for the future besides the squash based workflow?

**Comment by t-bre** [comment]
The article I linked is really good and I think explains the motivation / important considerations quite well.

I think with a squash workflow its particularly important to only work on one thing at a time in a PR. I mean that's probably obvious and a good idea regardless of merge strategy, but particularly with squashing because the overall change will be described by one commit on the main branch. 

GitHub should be set up so that the squashed commit has the message being the PR title and the extended message being the messages for all the commits that got squashed. This way on the main branch, you can still see the individual steps taken to implement the change but the overall history is kept clear and concise. Plus you can always look at the PR to see the individual commits, so the full history isn't lost.

**Comment by niketa282** [comment]
> The article I linked is really good and I think explains the motivation / important considerations quite well.
> 
> I think with a squash workflow its particularly important to only work on one thing at a time in a PR. I mean that's probably obvious and a good idea regardless of merge strategy, but particularly with squashing because the overall change will be described by one commit on the main branch.
> 
> GitHub should be set up so that the squashed commit has the message being the PR title and the extended message being the messages for all the commits that got squashed. This way on the main branch, you can still see the individual steps taken to implement the change but the overall history is kept clear and concise. Plus you can always look at the PR to see the individual commits, so the full history isn't lost.

Yup was a good article. So anything else on this PR or anything else for the future to keep in mind?

**Comment by t-bre** [comment]
Oh I see sorry didn't realise you were asking about this one specifically! No this is fine, I'll merge it.
